export const mockProducts = [
  { id: 1, name: 'Nova X1 Smartphone', category: 'Phones', category_slug: 'phones', description: 'Flagship performance, vivid OLED display and an all-day intelligent battery.', price: 799, stock: 24, accent: '#E9562A', featured: true, rating: 4.9, tags: ['phone','android','oled','5g'] },
  { id: 2, name: 'Pulse Pro Headphones', category: 'Audio', category_slug: 'audio', description: 'Immersive wireless audio with adaptive noise cancellation and 40-hour battery.', price: 249, stock: 38, accent: '#1D4ED8', featured: true, rating: 4.8, tags: ['headphones','wireless','noise cancelling'] },
  { id: 3, name: 'Arc 65W GaN Charger', category: 'Power', category_slug: 'power', description: 'Pocket-sized fast charger with dual USB-C ports for phone and laptop.', price: 59, stock: 76, accent: '#7C3AED', featured: true, rating: 4.7, tags: ['charger','usb-c','fast charging'] },
  { id: 4, name: 'Halo MagSafe Case', category: 'Accessories', category_slug: 'accessories', description: 'Slim shock-resistant phone case with a strong magnetic alignment ring.', price: 39, stock: 92, accent: '#DB2777', featured: false, rating: 4.6, tags: ['phone case','magsafe','protection'] },
  { id: 5, name: 'Volt 20K Power Bank', category: 'Power', category_slug: 'power', description: 'High-capacity power bank with a smart charge display and three ports.', price: 79, stock: 51, accent: '#0891B2', featured: false, rating: 4.7, tags: ['battery','power bank','travel'] },
  { id: 6, name: 'Echo Mini Speaker', category: 'Audio', category_slug: 'audio', description: 'Portable room-filling sound in a water-resistant palm-sized body.', price: 89, stock: 44, accent: '#EA580C', featured: true, rating: 4.5, tags: ['speaker','bluetooth','portable'] },
  { id: 7, name: 'Weave USB-C Cable', category: 'Accessories', category_slug: 'accessories', description: 'Durable braided 100W charging cable, tested for 30,000 bends.', price: 24, stock: 120, accent: '#475569', featured: false, rating: 4.8, tags: ['cable','usb-c','charging'] },
  { id: 8, name: 'Beam Smart Light Bar', category: 'Smart Home', category_slug: 'smart-home', description: 'Voice-ready ambient lighting with millions of colors and music sync.', price: 119, stock: 33, accent: '#16A34A', featured: false, rating: 4.4, tags: ['light','smart home','rgb'] },
  { id: 9, name: 'Orbit Wireless Pad', category: 'Accessories', category_slug: 'accessories', description: 'A low-profile 15W wireless charger with temperature protection.', price: 45, stock: 68, accent: '#0F766E', featured: false, rating: 4.5, tags: ['wireless charger','qi','desk'] },
];

export const mockCategories = ['Phones','Audio','Power','Accessories','Smart Home'].map((name, i) => ({ id: i + 1, name, slug: name.toLowerCase().replace(' ', '-'), product_count: [1,2,2,3,1][i] }));
